service: stefanini-challenge
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: sa-east-1

functions:
  listEmployers:
    handler: handler.listEmployers
    events:
      - http:
          path: employers
          method: get

  getEmployer:
    handler: handler.getEmployer
    events:
      - http:
          path: employers/{id}
          method: get
